config/routes.rb
Helloword::Application.routes.draw do

  devise_for :users, :controllers => {
    sessions:'users/sessions',
    registrations:'users/registrations'
  }

  #as :user do
  #  post 'sign_in_by_mobile_player' => "users/sessions#create_by_mobile_player", as:'user_session_by_mobile_player'
  #end
  
  get '/samples/file' => 'samples#file'
  post '/samples/file' => 'samples#update'

  root to:'dashboard#index'

  match '/dashboard/:book_id' => 'dashboard#index'

  resources :books do
    collection do
      post :sort
    end
    resources :words do
      collection do
        get :swipe
        delete :destroy_all
        match '/iframe' => 'words#iframe'
        post :validation
        post '/file_upload' => 'words#file_upload'
      end
    end
  end

  as :user do
    namespace :api do
      namespace :users do
        post 'sign_in_by_mobile' => "sessions#create_by_mobile"
      end
    end
  end

  namespace :api do
    post 'books' => 'books#index'
  end
end

app/models/word.rb
#coding: utf-8
class Word < ActiveRecord::Base

  attr_accessible :word, :answer, :user_id

  has_many :book_words, :dependent => :delete_all
  has_many :books, :through => :book_words

  #validates_length_of :word, :within => 1..40
  #validates_length_of :answer, :within => 1..255
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  layout :except => [:index]

  before_filter :authenticate_user!

  def index
    @book = current_user.books.find(params[:book_id])
    if @book.library?
      @words = current_user.words.find_all
    else
      @words = @book.words
    end
  end

  def show
    @word = Word.find(params[:id])
  end

  def swipe
    @words = Word.all
  end

  def new
    @word = Word.new
    @book = current_user.books.find(params[:book_id])
  end

  def edit
    @word = Word.find(params[:id])
  end

  def create
    @word = Word.new(params[:word])
    @word.user_id = current_user.id

    respond_to do |format|
      if @word.save
        if params[:book_id]
          BookWord.create(book_id:params[:book_id], word_id:@word.id)
        end
        flash[:notice] = 'success word created.'
        format.json { render json: @word, status: :created}
      else
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @word = Word.find(params[:id])
    if @word.update_attributes(params[:word])
      redirect_to word_path(@word)
    else
      render action: "edit"
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to words_path
  end

  #checkbox選択での複数削除
  def destroy_all

    words = []
    params[:words].split(',').each do |id|
      words << current_user.words.find(id)
    end
    
    book = Book.find params[:book_id]
    words.each do |w|
      if book.library? #ライブラリの場合は、マスター削除
        w.destroy
      else #Bookの場合は関連削除
        BookWord.where(book_id:params[:book_id], word_id:w.id).each {|_bw| _bw.destroy }
      end
    end

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def iframe
    @book = current_user.books.find params[:book_id]
    @words = @book.library? ? current_user.words.find_all : @book.words
  end

  def validation
    #TODO:yokohama ここでどんなファイルがきても内容をUTF-8に変換してあげる。
    @cv = CsvValidate.new(params[:file])
    @cv.validate
  end

  def file_upload
    book = current_user.books.find params[:book_id]
    @cv = CsvValidate.new(params[:file])
    new_record_count = Book::TOLERANCE - book.words.count
    @cv.to_words(current_user).each_with_index do |w, i|
      book.words << w if (i < new_record_count)
    end
    respond_to do |format|
      format.html{ head :no_content }
    end
  end

end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_file.html.erb
<!-- TODO:yokohama
アップロード時にファイルをUTF-8にコンバートする（テストやってない）
アップロード時にプログレスバーを表示する
ライブラリにアップロードしようとしている場合は、データが全て上書きされると注意をだす。
ライブラリにアップロードの場合は、モデルの関係等、サーバー側のロジックを見直す。
アップロードしたときに、ブックとワードの関係レコードが削除されていない。
-->
<h3>単語一括登録(CSV)</h3>
<div id="dropbox" class="hero-unit">
  <p class="message">ここにCSVをドロップ</p>
</div>

<div id="fileValidation" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="fileValidation" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="fileValidation">内容の確認</h3>
  </div>
  <div class="modal-body">
    <div id="message"></div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary" onclick="fup.upload_file();$(this).attr('disabled', true);">Save changes</button>
  </div>
</div>

<script>

function FileUpload(elm_id){
  var LOADED_FILE = []; //upload対象のfile一覧
  var LIMIT_IMG_W = 200; //画像fileはthumb nail表示しますが、
  var LIMIT_IMG_H = 200; //その際の最大表示サイズ
  //var UPLOAD_URL = '/samples/file';
  //var UPLOAD_URL = '/words/update';
  var TEXT_ENCODING = 'UTF-8';

  var FILE = null;
    
  //初期化
  this.init = function(elm_id){

    if( $("#" + elm_id).size() == 0 ){
      alert("can't find drop to element id : " + elm_id);
      return;
    }
    LOADED_FILE = [];
        
    //drop eventをセット.
    //※jquery.bindを使用すると、drop eventからdataTransferを取得不可。
    var this_obj = this;
    document.getElementById(elm_id).addEventListener('drop',
      function(e){this_obj.do_drop_file(e);},false);
      //default event & bubblingを中止
      $("#" + elm_id).bind('dragenter', function(e){e.preventDefault(); e.stopPropagation();})
        .bind('dragover', function(e){e.preventDefault(); e.stopPropagation();});
      $("html").bind('drop', function(e){e.preventDefault(); e.stopPropagation();})
        .bind('dragenter', function(e){e.preventDefault(); e.stopPropagation();})
        .bind('dragover', function(e){e.preventDefault(); e.stopPropagation();});
  };

  //fileがdropされると、呼ばれる
  this.do_drop_file = function(e){
    FILE = e.dataTransfer.files[0];

    var reader = new FileReader();
    reader.onloadend = function(e) {
      LOADED_FILE.push(e.target.result);
      fup.validation();
      //fup.upload_file();
    };

    reader.readAsText(FILE, "UIF-8");
  };

  this.validation = function(){
    if (this.can_upload_file()) {
      var data = new Object();
      data.file = LOADED_FILE;
      var this_obj = this;
      $.post(
        '/books/' + "<%= @book.id %>" + '/words/validation', 
        $.param(data,true), 
        function(data,textStatus){ this_obj.print_validation_message(data, textStatus); 
        }
      );
    }
  };

  //表示可能な画像fileの判定
  this.can_upload_file = function(){
    if (FILE.size == 0) {
      $('#fileValidation #fileValidation').empty();
      $('#fileValidation #message').empty();
      $('#fileValidation #fileValidation').append(FILE.name);
      $('#fileValidation #message').append('<p>ファイルが空です。</p>');
      $('#fileValidation').modal('show');
      return false;
    }
    if (FILE.type != 'text/csv'){
      $('#fileValidation #fileValidation').empty();
      $('#fileValidation #message').empty();
      $('#fileValidation #fileValidation').append(FILE.name);
      $('#fileValidation #message').append('<p>いまのところアップロードできるファイルはcsv形式のみです。</p>');
      $('#fileValidation').modal('show');
      return false;
    }
    return true;
  };

  //※html5では、FormDataというクラスが追加されたようですが
  //  firefox3.6では利用できないようなので、jquery.param()で送信.
  this.upload_file = function(){
    if (LOADED_FILE.length ==0) return;
    var data = new Object();
    data.file = LOADED_FILE;
    data.book_id = "<%= @book.id %>";

    var this_obj = this;
    $.post("/books/<%= @book.id %>/words/file_upload", $.param(data,true), function(data,textStatus){ this_obj.post_upload_file(data, textStatus); });
  };

  this.print_validation_message = function(data, textStatus){
    $('#fileValidation #fileValidation').empty();
    $('#fileValidation #message').empty();
    $('#fileValidation #fileValidation').append(FILE.name);
    $('#fileValidation #message').append(data);
    $('#fileValidation').modal('show');
  };

  this.post_upload_file = function(data,textStatus){ 
    $('#fileValidation').modal('hide');
    book_show(<%= @book.id %>);
  };
    
  //初期化実行
  this.init(elm_id);
};

var fup = new FileUpload('dropbox');
</script>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div class="alert alert-error">
      <ul>
        <% @word.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div>
      <%= f.text_field :keyword, placeholder: "単語", class: 'input-span1' %>
    </div>
    <div>
      <%= f.text_area :discription, placeholder: "答え", class: 'input-span1', rows: 8 %>
    </div>
    <div>
      <%= f.submit '登録', class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/words/_play.html.erb
<div style="margin-top:10px;margin-bottom:10px;">
  <center>
    <%= link_to image_tag('/assets/play.png'), swipe_words_path %>
  </center>
</div>

<!--
<div>
  <p>登録されている単語</p>
  <hr />
  <div style="word-break: break-all;">
    <ul>
      <%# @words.each do |word| %>
        <li><%#= link_to word.word, word %></li>
      <%# end %>
    </ul>
  </div>
</div>
-->

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/iframe.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>

<table class="table table-striped">
  <tbody>
    <% @words.each do |w| %>
      <div>
        <tr />
          <td width="180"><p style="word-break: break-all;"><font size="1"><%= w.word %></font></p></td>
          <td width="300"><p style="word-break: break-all;"><font size="1"><%= w.answer %></font></p></td>
          <td width="10"><div class="pull-right"><input type="checkbox" value="<%= w.id %>" class="word-checkbox" /></div></td>
        </tr>
      </div>
    <% end %>
  </tbody>
</table>

app/views/words/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span7">
      <div>
        <center style="margin-bottom:10px;">
          <form class="form-search">
            <div class="input-append">
              <input type="text" class="span12 search-query">
              <button class="btn" onclick="return(false);"><i class="icon-search"></i></button>
            </div>
          </form>
        </center>
      </div>
      <%#= render partial:'/words/play' %>
      <table class="table table-striped">
        <thead>
          <tr class="alert alert-success">
            <th>単語</th>
            <th>意味</th>
            <th>
              <div class="dropdown pull-right">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-wrench"></i></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li><a href="#" onclick="word_all_checked(true)" >全て選択</a></li>
                  <li><a href="#" onclick="word_all_checked(false)">選択解除</a></li>
                  <li><a href="#" onclick="word_destroy(<%= @book.id %>)">削除</a></li>
                </ul>
              </div>
            </th>
          </tr>
        </thead>
      </table>
      <iframe src="<%= iframe_book_words_path(:book_id => @book.id) %>" width="100%" height="400px">
      </iframe>
    </div>
    <div class="span5">
      <div id="word-new"></div>
    </div>
  </div>
</div>

<script>
  $(function () {
    word_new(<%= @book.id %>);
  });

  function word_new(id) {
    $.ajax({
       type: "GET",
       url: "/books/" + id + "/words/new",
       success: function(msg){
         $('#word-new').html(msg);
       }
     });
  };

  //BUG:一度全部解除すると、全て選択が機能しなくなる。
  function word_all_checked(b) {
    //$('.word-checkbox').each(function(){
    $('iframe:first').contents().find('.word-checkbox').each(function(){
      $(this).attr('checked', b);
    });
  }

  function word_destroy(book_id) {
    var ids = $('iframe:first').contents().find('.word-checkbox:checked').map(function() { return this.value; }).get().join();
    $.ajax({
       type: "DELETE",
       url: "/books/" + book_id + "/words/destroy_all",
       data: "words=" + ids,
       success: function(msg){
         book_show(book_id);
       }
     });
  }

</script>

app/views/words/new.html.erb
<div style="margin-bottom:40px;">
  <div id="word-new-message-area"></div>
  <% if @book.id.nil? %>
    <div class="alert alert-info">
      単語の追加は単語帳からおこなってください。
    </div>
  <% elsif @book.tolerance? %>
    <form id="word-new">
      <fieldset>
        <div>
          <input type="text" id="inputWord" name="book[word]" placeholder="単語" class="input-span1" />
        </div>
        <div>
          <textarea id="inputAnswer" name="book[answer]" placeholder="答え" class="input-span1" rows="3"></textarea>
        </div>
      </fieldset>
    </form>
    <button type="button" class="btn btn-primary pull-right" onclick="word_create(<%= @book.id %>);">単語の登録</button>
  <% else %>
    <p class="alert alert-error">単語帳に登録できる単語は200個までです。新しい単語を登録するには、単語帳から単語を削除してください。</p>
  <% end %>
</div>

<!--
<h3>エクセル一括登録</h3>
<div id="dropbox">
  <span class="message">Drop images here to upload. <br /><i>(they will only be visible to you)</i></span>
</div>
-->
<% if @book.tolerance? && !@book.id.nil? %>
  <%= render partial:'file' %>
<% end %>

<script>
  function word_create(id) {
    word = $('#word-new #inputWord').val();
    answer = $('#word-new #inputAnswer').val();

    $.ajax({
       type: "POST",
       url: "/books/" + id + "/words.json",
       data: "word[word]=" + word + "&word[answer]=" + answer,
       success: function(msg){
         //var notice = this.getResponseHeader("X-Flash-Notice");
         book_show(id);
       },
       error: function(msg){
         var error_msg = $.parseJSON(msg.responseText);
         var error_html = '<div class="alert alert-error">';
         for (i=0; i<error_msg.answer.length; i++) {
           error_html += '<p>Word ' + error_msg.word[i] + '</p>';
         }
         for (i=0; i<error_msg.answer.length; i++) {
           error_html += '<p>Answer ' + error_msg.answer[i] + '</p>';
         }
         error_html += '</div>';
         $('#word-new-message-area').html(error_html);
       }
    });
  }
</script>

app/views/words/show.html.erb
<div class="hero-unit" style="padding-top:4px;padding-bottom:40px;"> 
  <center><h1><%= @word.word %></h1></center>
  <hr />
  <p><li><%= @word.answer %></li></p>
  <p class="pull-right"><%= link_to '戻る', words_path %> | <%= link_to '編集', edit_word_path(@word) %> | <%= link_to '削除', word_path(@word), method: :delete, data: { confirm: 'この単語を本当に削除しますか？' } %></p>
</div>

app/views/words/swipe.html.erb
<style>
  #moge {
    height: 200px;
    margin-right: 10px;
    margin-left: 10px;
    padding-right: 10px;
    padding-left: 10px;
    background-color: red;
    word-break: break-all;
  }
  #hoge {
    font-size: xx-large;
    line-height: 40px;
  }
  /*
  @media (max-width: 480px) {
    #moge {
      background-color:black;
    }
  }
  @media (max-width: 320px) {
    #moge {
      background-color:black;
    }
  }
  */
</style>

<div id="slider">
  <ul>
    <% @words.each_with_index do |w, i| %>
      <div style="<%= i == 0 ? 'display:block' : 'display:none' %>">
        <div id="moge">
          <center><%= "#{i+1}/#{@words.size}" %></center>
          <p id="hoge"><%= w.word %></p>
        </div>
      </div>
    <% end %>
  </ul>
</div>
<a href='#' onclick='slider.prev();return false;'>●</a>
<a href='#' onclick='slider.next();return false;'>●</a>
<i class="icon-volume-down"></i>
<i class="icon-retweet"></i>

<script>
  var slider = new Swipe(document.getElementById('slider'));
</script>

app/views/words/validation.html.erb
<center><p><%= @cv.records.size %>件の単語</p></center>
<% if @cv.error_count > 0 %>
  <div class="label label-important" style="margin-top:10px;margin-bottom:10px;"><%= @cv.error_count %>件の不正なデータがあります。<br />赤いレコードはデータがおかしいため保存のさいにスキップされます。</div>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>単語</th>
      <th>答え</th>
    </tr>
  </thead>
  <tbody>
    <% @cv.records.each do |r| %>
      <% if r[:error_line_no] %>
        <tr class="alert alert-error">
          <td><%= r[:word] %></td>
          <td><%= r[:answer] %></td>
        </tr>
      <% else %>
        <tr>
          <td><%= r[:word] %></td>
          <td><%= r[:answer] %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>